# Custom Language File for Launcher Customizer

[ejs.app]
title = "Tegan® Launcher"

[ejs.landing]
mediaGitHubURL = "#"
mediaXURL = "#"
mediaInstagramURL = "#"
mediaYouTubeURL = "#"
mediaDiscordURL = "#"

[ejs.settings]
sourceGithubLink = "#"
supportLink = "#"

[ejs.welcome]
welcomeHeader = "BENVENUTO/A SU TEGAN® LAUNCHER"
welcomeDescription = "Sei a pochi passi da Tegan® Launcher"
welcomeDescCTA = "Copyright © 2025 Tegan Studios®"
